### ISSUE TITLE
Url image on CSS not fingerprinted

### ISSUE THREAD

**Issue by pichotweb** [rails/sprockets-rails#101]
I'm using sprockets 2.10.1 with rails 4, and when i use a tag `image-url` on a SCSS file, this does not return to me the fingerprinted version of the image, only the real name.

My image is in "app/assets/image/icons/social/facebook.png", when i compile it, it live in:
 " public/assets/icons/social/facebook-73d00144595b5a4c37b816604c2fe6ed.png "

The css file is in "vendor/assets/stylesheets/app.css.scss", and the line is:

``` scss
.social_facebook { background: image-url("icons/social/facebook.png") no-repeat; }
```

And i call it on the css manifest file this way:

``` scss
*= require app
```

And the final css file gives me this piece of code:

``` scss
.social_facebook {
  background: url(/assets/icons/social/facebook.png) no-repeat; }
```

Note the non fingerprinted call to the image.

I've tried a lot of configurations, only the live compilation `config.assets.compile = true` solves the problem, but it is not the best way to let a app on production due to performance issues.

How can i solve this?
Cheers.
