### ISSUE TITLE
image-url ignore RAILS_RELATIVE_URL_ROOT

### ISSUE THREAD

**Issue by lkmatsumura** [rails/sprockets-rails#108]
Example:
test.css.scss

``` scss
.test {
  background-image: image-url('test.png');
  background-image: asset-url('test.png');
}
```

Running rake assets:precompile with RAILS_RELATIVE_URL_ROOT the sub-uri isn´t added to the result url generated with image-url function.
asset-url works fine.

Tested in rails 4.0.2
