### ISSUE TITLE
Compass font-face mixin raises Sprockets::Rails::Helper::AbsoluteAssetPathError with sprockets-rails 2.1.4

### ISSUE THREAD

**Issue by istvanp** [rails/sprockets-rails#170]
```
Sprockets::Rails::Helper::AbsoluteAssetPathError at /
Asset names passed to helpers should not include the "/assets/" prefix.
Instead of "/assets/picto-foundry-general.woff", use "picto-foundry-general.woff"
```

``` css
@import "compass";
@include font-face("Picto Foundry General", font_files(
        font-path("picto-foundry-general.woff"),
        font-path("picto-foundry-general.ttf"),
        font-path("picto-foundry-general.svg")),
        font-path("picto-foundry-general.eot"), normal, normal);
```

Workaround:

``` css
@font-face {
    font-family: 'Picto Foundry General';
    src: font-url('picto-foundry-general.eot');
    src: font-url('picto-foundry-general.eot?#iefix') format("embedded-opentype"),
    font-url('picto-foundry-general.woff') format("woff"),
    font-url('picto-foundry-general.ttf') format("truetype"),
    font-url('picto-foundry-general.svg#picto-foundry-general') format("svg");
    font-weight: normal;
    font-style: normal;
}
```

I am not sure which is really at fault here but it makes sense to report it where the error is raised :sweat_smile:
